---
- name: Add PostgreSQL Apt Repository (1)
  become: true
  become_user: root
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'

- name: Add PostgreSQL Apt Repository (2)
  become: true
  become_user: root
  shell: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -

- name: Install PostgreSQL
  become: true
  become_user: root
  apt: name={{item}} state=installed update_cache=true
  with_items:
       - postgresql
       - postgresql-contrib
  register: installpostgresql
